version: '3.8'
services:
  dev-db:
    image: mysql
    ports:
      - 4242:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_DB: nest
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - my_network
networks:
  my_network: